version: "3.9"

services:
  time.ir_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: time.ir_api
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - CONSOLE_LOG_LEVEL=${CONSOLE_LOG_LEVEL:-debug}
      - FILE_LOG_LEVEL=${FILE_LOG_LEVEL:-error}
    volumes:
      - $PWD/logs:/logs
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    restart: unless-stopped